# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chaos Monkey
email: cha00smonk3y@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Starting guides, cool tips or simply random thoughts about the tools and software that allow to get a data project from R&D to production. Let's dive in !
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.chaosmonkey.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  simplepat

# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-avatar
  - jekyll-seo-tag
  - jekyll-sitemap
  
  
# Format of the permalinks
permalink:             pretty

paginate: 5
paginate_path: '/page-:num/'

# Sidebar settings
defaults:
  - scope:
      path: about.md
    values:
      menu: true
      order: 1
      

# Setting recap pages for catagories & tags
collections:
  featured_categories:
    permalink:         /category/:name/
    output:            true
  featured_tags:
    permalink:         /tag/:name/
    output:            true
    
    
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
